# Generated by Django 5.1.1 on 2024-09-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
